// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TechShop.Models;

#nullable disable

namespace TechShop.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250512183552_AddTrangthaiToHoadon")]
    partial class AddTrangthaiToHoadon
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TechShop.Models.Account", b =>
                {
                    b.Property<int>("MaTk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaTK");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTk"));

                    b.Property<string>("Gmail")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasDefaultValue("");

                    b.Property<string>("PasswordTk")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("PasswordTK");

                    b.Property<int>("RoleTk")
                        .HasColumnType("int")
                        .HasColumnName("RoleTK");

                    b.Property<string>("UsernameTk")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("UsernameTK");

                    b.HasKey("MaTk")
                        .HasName("PK__Accounts__27250070C97282C8");

                    b.HasIndex(new[] { "UsernameTk" }, "UQ__Accounts__15DC27FC668419E0")
                        .IsUnique();

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("TechShop.Models.Banphim", b =>
                {
                    b.Property<string>("MaBp")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("MaBP");

                    b.Property<bool>("DenledBp")
                        .HasColumnType("bit")
                        .HasColumnName("DenledBP");

                    b.Property<int>("GiaBp")
                        .HasColumnType("int")
                        .HasColumnName("GiaBP");

                    b.Property<string>("HangBp")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("HangBP");

                    b.Property<string>("KieuketnoiBp")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("KieuketnoiBP");

                    b.Property<string>("LoaiBp")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("LoaiBP");

                    b.Property<string>("MaHh")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("MaHH");

                    b.Property<string>("MaNcc")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("MaNCC");

                    b.Property<string>("MaPlsp")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("MaPLSP");

                    b.Property<DateOnly?>("NgaysanxuatBp")
                        .HasColumnType("date")
                        .HasColumnName("NgaysanxuatBP");

                    b.Property<string>("TenBp")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TenBP");

                    b.Property<string>("TinhtrangBp")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("TinhtrangBP");

                    b.Property<string>("XuatxuBp")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("XuatxuBP");

                    b.HasKey("MaBp")
                        .HasName("PK__Banphim__272475AB37053E7E");

                    b.HasIndex("MaHh");

                    b.HasIndex("MaPlsp");

                    b.ToTable("Banphim");
                });

            modelBuilder.Entity("TechShop.Models.ChitietHd", b =>
                {
                    b.Property<string>("MaCthd")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("MaCTHD");

                    b.Property<int>("Dongia")
                        .HasColumnType("int");

                    b.Property<string>("MaHd")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("MaHD");

                    b.Property<string>("MaHh")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("MaHH");

                    b.Property<int>("Soluong")
                        .HasColumnType("int");

                    b.HasKey("MaCthd")
                        .HasName("PK__ChitietH__1E4FA771E41E6CA7");

                    b.HasIndex("MaHd");

                    b.HasIndex("MaHh");

                    b.ToTable("ChitietHD");
                });

            modelBuilder.Entity("TechShop.Models.Hanghoa", b =>
                {
                    b.Property<string>("MaHh")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("MaHH");

                    b.Property<int>("GiaHh")
                        .HasColumnType("int")
                        .HasColumnName("GiaHH");

                    b.Property<string>("LoaiHh")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("LoaiHH");

                    b.Property<string>("MaNcc")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("MaNCC");

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Soluongton")
                        .HasColumnType("int");

                    b.Property<string>("TenHh")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TenHH");

                    b.HasKey("MaHh")
                        .HasName("PK__Hanghoa__2725A6E45E5FAD4F");

                    b.HasIndex("MaNcc");

                    b.ToTable("Hanghoa");
                });

            modelBuilder.Entity("TechShop.Models.HinhAnhSanPham", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DuongDan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaHh")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("HinhAnhSanPhams");
                });

            modelBuilder.Entity("TechShop.Models.Hoadon", b =>
                {
                    b.Property<string>("MaHd")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("MaHD");

                    b.Property<string>("Ghichu")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("MaKh")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("MaKH");

                    b.Property<string>("MaNv")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("MaNV");

                    b.Property<DateOnly>("NgaylapHd")
                        .HasColumnType("date")
                        .HasColumnName("NgaylapHD");

                    b.Property<decimal?>("TongtienHd")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("TongtienHD");

                    b.Property<string>("Trangthai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Trangthai");

                    b.HasKey("MaHd")
                        .HasName("PK__Hoadon__2725A6E0A90BC80A");

                    b.HasIndex("MaKh");

                    b.HasIndex("MaNv");

                    b.ToTable("Hoadon");
                });

            modelBuilder.Entity("TechShop.Models.Khachhang", b =>
                {
                    b.Property<string>("MaKh")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("MaKH");

                    b.Property<string>("DiachiKh")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("DiachiKH");

                    b.Property<string>("FulltenKh")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("FulltenKH");

                    b.Property<int?>("MaTk")
                        .HasColumnType("int")
                        .HasColumnName("MaTK");

                    b.Property<string>("SdtKh")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("SdtKH");

                    b.HasKey("MaKh")
                        .HasName("PK__Khachhan__2725CF1E72F421B0");

                    b.HasIndex("MaTk");

                    b.HasIndex(new[] { "FulltenKh" }, "UQ__Khachhan__D6512A83F236E621")
                        .IsUnique();

                    b.ToTable("Khachhang");
                });

            modelBuilder.Entity("TechShop.Models.Laptop", b =>
                {
                    b.Property<string>("MaLt")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("MaLT");

                    b.Property<int>("GiaLt")
                        .HasColumnType("int")
                        .HasColumnName("GiaLT");

                    b.Property<string>("HangLt")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("HangLT");

                    b.Property<string>("KichthuocLt")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("KichthuocLT");

                    b.Property<string>("MaHh")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("MaHH");

                    b.Property<string>("MaNcc")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("MaNCC");

                    b.Property<string>("MaPlsp")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("MaPLSP");

                    b.Property<DateOnly?>("NgaysanxuatLt")
                        .HasColumnType("date")
                        .HasColumnName("NgaysanxuatLT");

                    b.Property<string>("OcungLt")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("OcungLT");

                    b.Property<string>("RamLt")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("RamLT");

                    b.Property<string>("TenLt")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TenLT");

                    b.Property<string>("TinhtrangLt")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("TinhtrangLT");

                    b.Property<string>("XuatxuLt")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("XuatxuLT");

                    b.HasKey("MaLt")
                        .HasName("PK__Laptop__2725C773763C2B6D");

                    b.HasIndex("MaHh");

                    b.HasIndex("MaPlsp");

                    b.HasIndex(new[] { "TenLt" }, "UQ__Laptop__4CF9A468F04DF093")
                        .IsUnique();

                    b.ToTable("Laptop");
                });

            modelBuilder.Entity("TechShop.Models.Loa", b =>
                {
                    b.Property<string>("MaLoa")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("CongsuatLoa")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("GiaLoa")
                        .HasColumnType("int");

                    b.Property<string>("HangLoa")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("KieuketnoiLoa")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaHh")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("MaHH");

                    b.Property<string>("MaNcc")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("MaNCC");

                    b.Property<string>("MaPlsp")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("MaPLSP");

                    b.Property<DateOnly?>("NgaysanxuatLoa")
                        .HasColumnType("date");

                    b.Property<string>("TenLoa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TinhtrangLoa")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("XuatxuLoa")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaLoa")
                        .HasName("PK__Loa__3B98D240FBD17876");

                    b.HasIndex("MaHh");

                    b.HasIndex("MaPlsp");

                    b.ToTable("Loa");
                });

            modelBuilder.Entity("TechShop.Models.Manhinh", b =>
                {
                    b.Property<string>("MaMh")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("MaMH");

                    b.Property<string>("DoPhanGiaiMh")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("DoPhanGiaiMH");

                    b.Property<int>("GiaMh")
                        .HasColumnType("int")
                        .HasColumnName("GiaMH");

                    b.Property<string>("HangMh")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("HangMH");

                    b.Property<string>("KichthuocMh")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("KichthuocMH");

                    b.Property<string>("MaHh")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("MaHH");

                    b.Property<string>("MaNcc")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("MaNCC");

                    b.Property<string>("MaPlsp")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("MaPLSP");

                    b.Property<DateOnly?>("NgaysanxuatMh")
                        .HasColumnType("date")
                        .HasColumnName("NgaysanxuatMH");

                    b.Property<string>("TansoMh")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("TansoMH");

                    b.Property<string>("TenMh")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TenMH");

                    b.Property<string>("TinhtrangMh")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("TinhtrangMH");

                    b.Property<string>("XuatxuMh")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("XuatxuMH");

                    b.HasKey("MaMh")
                        .HasName("PK__Manhinh__2725DFD969530BD5");

                    b.HasIndex("MaHh");

                    b.HasIndex("MaPlsp");

                    b.ToTable("Manhinh");
                });

            modelBuilder.Entity("TechShop.Models.Nhacungcap", b =>
                {
                    b.Property<string>("MaNcc")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("MaNCC");

                    b.Property<string>("DiachiNcc")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("DiachiNCC");

                    b.Property<string>("EmailNcc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("EmailNCC");

                    b.Property<string>("Nguoilienlac")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SdtNcc")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("SdtNCC");

                    b.Property<string>("TenNcc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TenNCC");

                    b.HasKey("MaNcc")
                        .HasName("PK__Nhacungc__3A185DEBBBD7F3FE");

                    b.ToTable("Nhacungcap");
                });

            modelBuilder.Entity("TechShop.Models.Nhanvien", b =>
                {
                    b.Property<string>("MaNv")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("MaNV");

                    b.Property<string>("DiachiNv")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("DiachiNV");

                    b.Property<string>("EmailNv")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("EmailNV");

                    b.Property<string>("FulltenNv")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("FulltenNV");

                    b.Property<int?>("MaTk")
                        .HasColumnType("int")
                        .HasColumnName("MaTK");

                    b.Property<string>("SdtNv")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("SdtNV");

                    b.HasKey("MaNv")
                        .HasName("PK__Nhanvien__2725D70A04C9B38A");

                    b.HasIndex("MaTk");

                    b.ToTable("Nhanvien");
                });

            modelBuilder.Entity("TechShop.Models.PhanloaiSp", b =>
                {
                    b.Property<string>("MaPlsp")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("MaPLSP");

                    b.Property<string>("MoTaPlsp")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("MoTaPLSP");

                    b.Property<string>("TenPlsp")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TenPLSP");

                    b.HasKey("MaPlsp")
                        .HasName("PK__Phanloai__BD3992AFC28AFCE5");

                    b.ToTable("PhanloaiSP");
                });

            modelBuilder.Entity("TechShop.Models.Tainghe", b =>
                {
                    b.Property<string>("MaTn")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("MaTN");

                    b.Property<int>("GiaTn")
                        .HasColumnType("int")
                        .HasColumnName("GiaTN");

                    b.Property<string>("HangTn")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("HangTN");

                    b.Property<string>("KieuketnoiTn")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("KieuketnoiTN");

                    b.Property<string>("LoaiTn")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("LoaiTN");

                    b.Property<string>("MaHh")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("MaHH");

                    b.Property<string>("MaNcc")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("MaNCC");

                    b.Property<string>("MaPlsp")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("MaPLSP");

                    b.Property<DateOnly?>("NgaysanxuatTn")
                        .HasColumnType("date")
                        .HasColumnName("NgaysanxuatTN");

                    b.Property<string>("PinTn")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("PinTN");

                    b.Property<string>("TenTn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TenTN");

                    b.Property<string>("TinhtrangTn")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("TinhtrangTN");

                    b.Property<string>("TrongluongTn")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TrongluongTN");

                    b.Property<string>("XuatxuTn")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("XuatxuTN");

                    b.HasKey("MaTn")
                        .HasName("PK__Tainghe__27250073255F3EB0");

                    b.HasIndex("MaHh");

                    b.HasIndex("MaPlsp");

                    b.ToTable("Tainghe");
                });

            modelBuilder.Entity("TechShop.ViewModels.ProductViewModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Gia")
                        .HasColumnType("int");

                    b.Property<string>("HinhAnh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Loai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaNcc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Soluongton")
                        .HasColumnType("int");

                    b.Property<string>("Ten")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("TechShop.Models.Banphim", b =>
                {
                    b.HasOne("TechShop.Models.Hanghoa", "MaHhNavigation")
                        .WithMany("Banphims")
                        .HasForeignKey("MaHh")
                        .HasConstraintName("FK__Banphim__MaHH__18EBB532");

                    b.HasOne("TechShop.Models.PhanloaiSp", "MaPlspNavigation")
                        .WithMany("Banphims")
                        .HasForeignKey("MaPlsp")
                        .HasConstraintName("FK__Banphim__MaPLSP__70DDC3D8");

                    b.Navigation("MaHhNavigation");

                    b.Navigation("MaPlspNavigation");
                });

            modelBuilder.Entity("TechShop.Models.ChitietHd", b =>
                {
                    b.HasOne("TechShop.Models.Hoadon", "MaHdNavigation")
                        .WithMany("ChitietHds")
                        .HasForeignKey("MaHd")
                        .IsRequired()
                        .HasConstraintName("FK__ChitietHD__MaHD__2B0A656D");

                    b.HasOne("TechShop.Models.Hanghoa", "MaHhNavigation")
                        .WithMany("ChitietHds")
                        .HasForeignKey("MaHh")
                        .IsRequired()
                        .HasConstraintName("FK__ChitietHD__MaHH__2BFE89A6");

                    b.Navigation("MaHdNavigation");

                    b.Navigation("MaHhNavigation");
                });

            modelBuilder.Entity("TechShop.Models.Hanghoa", b =>
                {
                    b.HasOne("TechShop.Models.Nhacungcap", "MaNccNavigation")
                        .WithMany("Hanghoas")
                        .HasForeignKey("MaNcc")
                        .HasConstraintName("FK__Hanghoa__MaNCC__160F4887");

                    b.Navigation("MaNccNavigation");
                });

            modelBuilder.Entity("TechShop.Models.Hoadon", b =>
                {
                    b.HasOne("TechShop.Models.Khachhang", "MaKhNavigation")
                        .WithMany("Hoadons")
                        .HasForeignKey("MaKh")
                        .HasConstraintName("FK__Hoadon__MaKH__6754599E");

                    b.HasOne("TechShop.Models.Nhanvien", "MaNvNavigation")
                        .WithMany("Hoadons")
                        .HasForeignKey("MaNv")
                        .HasConstraintName("FK__Hoadon__MaNV__68487DD7");

                    b.Navigation("MaKhNavigation");

                    b.Navigation("MaNvNavigation");
                });

            modelBuilder.Entity("TechShop.Models.Khachhang", b =>
                {
                    b.HasOne("TechShop.Models.Account", "MaTkNavigation")
                        .WithMany("Khachhangs")
                        .HasForeignKey("MaTk")
                        .HasConstraintName("FK__Khachhang__MaTK__4D94879B");

                    b.Navigation("MaTkNavigation");
                });

            modelBuilder.Entity("TechShop.Models.Laptop", b =>
                {
                    b.HasOne("TechShop.Models.Hanghoa", "MaHhNavigation")
                        .WithMany("Laptops")
                        .HasForeignKey("MaHh")
                        .HasConstraintName("FK__Laptop__MaHH__17036CC0");

                    b.HasOne("TechShop.Models.PhanloaiSp", "MaPlspNavigation")
                        .WithMany("Laptops")
                        .HasForeignKey("MaPlsp")
                        .HasConstraintName("FK__Laptop__MaPLSP__6EF57B66");

                    b.Navigation("MaHhNavigation");

                    b.Navigation("MaPlspNavigation");
                });

            modelBuilder.Entity("TechShop.Models.Loa", b =>
                {
                    b.HasOne("TechShop.Models.Hanghoa", "MaHhNavigation")
                        .WithMany("Loas")
                        .HasForeignKey("MaHh")
                        .HasConstraintName("FK__Loa__MaHH__17F790F9");

                    b.HasOne("TechShop.Models.PhanloaiSp", "MaPlspNavigation")
                        .WithMany("Loas")
                        .HasForeignKey("MaPlsp")
                        .HasConstraintName("FK__Loa__MaPLSP__71D1E811");

                    b.Navigation("MaHhNavigation");

                    b.Navigation("MaPlspNavigation");
                });

            modelBuilder.Entity("TechShop.Models.Manhinh", b =>
                {
                    b.HasOne("TechShop.Models.Hanghoa", "MaHhNavigation")
                        .WithMany("Manhinhs")
                        .HasForeignKey("MaHh")
                        .HasConstraintName("FK__Manhinh__MaHH__19DFD96B");

                    b.HasOne("TechShop.Models.PhanloaiSp", "MaPlspNavigation")
                        .WithMany("Manhinhs")
                        .HasForeignKey("MaPlsp")
                        .HasConstraintName("FK_Manhinh_PhanloaiSP");

                    b.Navigation("MaHhNavigation");

                    b.Navigation("MaPlspNavigation");
                });

            modelBuilder.Entity("TechShop.Models.Nhanvien", b =>
                {
                    b.HasOne("TechShop.Models.Account", "MaTkNavigation")
                        .WithMany("Nhanviens")
                        .HasForeignKey("MaTk")
                        .HasConstraintName("FK__Nhanvien__MaTK__5165187F");

                    b.Navigation("MaTkNavigation");
                });

            modelBuilder.Entity("TechShop.Models.Tainghe", b =>
                {
                    b.HasOne("TechShop.Models.Hanghoa", "MaHhNavigation")
                        .WithMany("Tainghes")
                        .HasForeignKey("MaHh")
                        .HasConstraintName("FK_Tainghe_Hanghoa");

                    b.HasOne("TechShop.Models.PhanloaiSp", "MaPlspNavigation")
                        .WithMany("Tainghes")
                        .HasForeignKey("MaPlsp")
                        .HasConstraintName("FK__Tainghe__MaPLSP__6FE99F9F");

                    b.Navigation("MaHhNavigation");

                    b.Navigation("MaPlspNavigation");
                });

            modelBuilder.Entity("TechShop.Models.Account", b =>
                {
                    b.Navigation("Khachhangs");

                    b.Navigation("Nhanviens");
                });

            modelBuilder.Entity("TechShop.Models.Hanghoa", b =>
                {
                    b.Navigation("Banphims");

                    b.Navigation("ChitietHds");

                    b.Navigation("Laptops");

                    b.Navigation("Loas");

                    b.Navigation("Manhinhs");

                    b.Navigation("Tainghes");
                });

            modelBuilder.Entity("TechShop.Models.Hoadon", b =>
                {
                    b.Navigation("ChitietHds");
                });

            modelBuilder.Entity("TechShop.Models.Khachhang", b =>
                {
                    b.Navigation("Hoadons");
                });

            modelBuilder.Entity("TechShop.Models.Nhacungcap", b =>
                {
                    b.Navigation("Hanghoas");
                });

            modelBuilder.Entity("TechShop.Models.Nhanvien", b =>
                {
                    b.Navigation("Hoadons");
                });

            modelBuilder.Entity("TechShop.Models.PhanloaiSp", b =>
                {
                    b.Navigation("Banphims");

                    b.Navigation("Laptops");

                    b.Navigation("Loas");

                    b.Navigation("Manhinhs");

                    b.Navigation("Tainghes");
                });
#pragma warning restore 612, 618
        }
    }
}
